### PR TITLE
Cleanup CraftTweaker integration code

### PR DESCRIPTION
**Pull request by pupnewfster**
Did some work that should make parts of #16 easier to implement. Also lowered the amount of log spam. (The majority of the remaining log spam will be removed when Jared gets a chance to release a new version of MTLib)

- Refactored the crafttweaker integration to remove duplicate code (It now relies on generics and a helper class instead)
- Lowered the number of unchecked cast warnings down to 2
- Improved the warning message for when no recipe of a given type was found.
- Don't spam the CraftTweaker log with 0 recipes removed, when we already are showing a warning message for no recipes found.
- Made CraftTweakerGasStack implement all methods that IIngredient declares in newer versions of CrT

### CODE REVIEW

**Comment by dizzyd** [comment]
This looks pretty good and I'm going to merge into 9.4.19, beta 1. 

In the future if you would please avoid committing files that are ONLY variable name changes or formatting changes, that would be ideal - makes it hard to pick through the actual changes. :)

**Comment by dizzyd** [comment]
Merged.

**Comment by pupnewfster** [comment]
Ya sorry about that, some of the code when I was copy pasting things around deduplicating code was formatted strangely, so I just ran my formatter on the entire package forgetting that it would make the diff harder to read.

**Comment by dizzyd** [comment]
No worries. If you get a chance, please pull master and validate everything you changed is still working and also play around with sound a bit?

**Pull request closed without merging**
